import 'styles/globals.css'
import Header from '@/components/Header'
import PromptInput from '@/components/PromptInput'

export const metadata = {
  title: 'Image Generator',
  description:
    'Generated by create next app and implemented with a IA to generate images'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Header />

        <PromptInput />

        {children}
      </body>
    </html>
  )
}
